### ISSUE TITLE
How much memory is needed to train and test the 3DitScene Model? 

### ISSUE THREAD

**Issue by ZhaoLongjiea** [zqh0253/3DitScene#10]
The paper does not specify the computational requirements. How much memory is needed to train and test the 3DitScene Model? Currently, I have only one 4090 GPU with 24GB of memory.
Thank you.

**Comment by zqh0253** [comment]
Hi, 24GB is enough.

**Comment by ZhaoLongjiea** [comment]
> Hi, 24GB is enough.

Thank you, when I tested this model, I found the max is 19GB.
