### ISSUE TITLE
When I want to delete this bear in the picture, it failed.

### ISSUE THREAD

**Issue by ZhaoLongjiea** [zqh0253/3DitScene#11]
When I want to test the inpainting ability, and I revised the prompt as 'delete the bear'. Nothing happened. I still got a photo with this bear. And after I check the scene_lang.yaml. How to modificate the command line? Below is the command and photo after I used 'delete the bear'.

python -u launch.py --config custom/threestudio-3dgs/configs/scene_lang.yaml --train --gpu 0 tag=3DitScene "system.geometry.geometry_convert_from=depth:assets/teddy.png" "system.geometry.ooi_bbox=[122,119,387,495]" "system.prompt_processor.prompt=delete the bear" "system.empty_prompt=Times Square, out of focus" "system.side_prompt=Times Square, out of focus"

![outpaint_0](https://github.com/user-attachments/assets/99d3f134-d56e-4c2c-941e-e3de7065ee7e)

**Comment by zqh0253** [comment]
The prompt should be used to describe the image itself, not the editing purpose. To edit the image, such as removing the foreground bear, you need to manipulate the 3D Gaussians associated with the object.

In [GaussianBaseModel](https://github.com/zqh0253/3DitScene/blob/main/custom/threestudio-3dgs/geometry/gaussian_base.py#L358), `ooi_masks_0` provides the mask for the foreground object, while `_opacity_mask` defines the opacity of each Gaussian. To remove the object, you can set the opacity of foreground object to zero.

**Comment by xi-zc** [comment]
> The prompt should be used to describe the image itself, not the editing purpose. To edit the image, such as removing the foreground bear, you need to manipulate the 3D Gaussians associated with the object.
> 
> In [GaussianBaseModel](https://github.com/zqh0253/3DitScene/blob/main/custom/threestudio-3dgs/geometry/gaussian_base.py#L358), `ooi_masks_0` provides the mask for the foreground object, while `_opacity_mask` defines the opacity of each Gaussian. To remove the object, you can set the opacity of foreground object to zero.

Thank you for your guidance.
I have a follow-up question regarding the specific implementation. Are you suggesting that to remove the foreground object, I should set self.geometry._opacity_mask[self.geometry.ooi_masks_0] = 0 directly within the scene_lang.py? I want to confirm if my understanding of your suggestion is correct, and if this is the precise location or method to achieve the desired effect.

**Comment by zqh0253** [comment]
You can add it in your inference script.

**Comment by xi-zc** [comment]
> You can add it in your inference script.

Thank you very much for your helpful suggestion.
Building on this, I was wondering if it's also possible to obtain a mesh surface representation as an output from your pipeline, in addition to the current point cloud output (point_cloud.ply)? Or perhaps is there a recommended way to convert the output to a mesh?
