### ISSUE TITLE
How can I do some other operations?

### ISSUE THREAD

**Issue by Nora202** [zqh0253/3DitScene#12]
Hi, just want to ask, when I try to rotate the teddy or replace the teddy, it doesn't work. Is there something wrong with my command line and how should I change it?

Here is my command line for rotate the teddy:
python -u launch.py --config custom/threestudio-3dgs/configs/scene_lang.yaml  --train --gpu 0 tag=3DitScene 
system.geometry.geometry_convert_from=depth:assets/teddy.png system.geometry.ooi_bbox=[122,119,387,495]
system.prompt_processor.prompt="a teddy bear in Times Square" system.empty_prompt="Times Square, out of focus" system.side_prompt="Teddy bear, rotate" 

and for replace teddy:
 python -u launch.py --config custom/threestudio-3dgs/configs/scene_lang.yaml  --train --gpu 0 tag=3DitScene system.geometry.geometry_convert_from=depth:assets/teddy.png system.geometry.ooi_bbox=[122,119,387,495] system.
prompt_processor.prompt="a teddy bear in Times Square" system.empty_prompt="Times Square, out of focus" system.side_prompt="Replace the teddy bear with cat"

**Comment by zqh0253** [comment]
https://github.com/zqh0253/3DitScene/issues/11
