### ISSUE TITLE
How can I do a replacement operation

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [zqh0253/3DitScene#15]
Hi!
such as this command:
python -u launch.py --config custom/threestudio-3dgs/configs/scene_lang.yaml  --train --gpu 0 tag=3DitScene 
system.geometry.geometry_convert_from=depth:assets/teddy.png system.geometry.ooi_bbox=[122,119,387,495]
system.prompt_processor.prompt="a teddy bear in Times Square" system.empty_prompt="Times Square, out of focus" system.side_prompt="Times Square, out of focus"
If I want to replace the teddy bear to a polar bear,can the algorithm complete this operation
and how to achive it

**Comment by zqh0253** [comment]
You can set `empty_prompt` for replacement operation, for example "a rabbit in Times Square".

**Comment by ALEX5874** [comment]
> You can set `empty_prompt` for replacement operation, for example "a rabbit in Times Square".

Hi, I have tried this command, but it still output the same result. Did I misunderstand sth?
