### ISSUE TITLE
About the prompt

### ISSUE THREAD

**Issue by ALEX5874** [zqh0253/3DitScene#16]
Hi, you have done an amazing work!
I have a question when I use your code about how to replicate the effect in your paper like the "remove" and the "move" and maybe "replace" operation. And also the camera operations.
Could you give more details about the three promts in the example?

python -u launch.py --config custom/threestudio-3dgs/configs/scene_lang.yaml  --train --gpu 0 tag=3DitScene 
system.geometry.geometry_convert_from=depth:assets/teddy.png system.geometry.ooi_bbox=[122,119,387,495]
system.prompt_processor.prompt="a teddy bear in Times Square" system.empty_prompt="Times Square, out of focus" system.side_prompt="Times Square, out of focus"

**Comment by ALEX5874** [comment]
I have tried the behind instruction, and it didn't work. How should I refine it?

python -u launch.py --config custom/threestudio-3dgs/configs/scene_lang.yaml  --train --gpu 3 tag=3DitScene system.geometry.geometry_convert_from=depth:assets/teddy.png system.geometry.ooi_bbox=[122,119,387,495] system.prompt_processor.prompt="a teddy bear in Times Square" system.empty_prompt="Move the teddy bear, and rotate the camera" system.side_prompt="Times square, out of focus"

**Comment by ALEX5874** [comment]
Hi,  I have read some issues that has been closed. It seems that the core is the "ooi_msk" parameter, which comes from the sam model. I  have a question: why I can't use prompt to realise the effect in your paper directly? Because I haven't found any code related to how the prompt related to the "ooi_mask".

**Comment by zqh0253** [comment]
The prompt is used to synthesize the 3D scene. For editing, you need to control the 3D Gaussians by `ooi_masks`(https://github.com/zqh0253/3DitScene/issues/11#issuecomment-2274824411).

**Comment by ALEX5874** [comment]
Thanks for your reply. But in your paper, the prompt could control the edit process like:remove or move , how can I achieve that? Could you give me more details?

**Comment by ALEX5874** [comment]
> The prompt is used to synthesize the 3D scene. For editing, you need to control the 3D Gaussians by `ooi_masks`([#11 (comment)](https://github.com/zqh0253/3DitScene/issues/11#issuecomment-2274824411)).

You are so kind to reply so fast. I have another question: in the early issue which has been closed, you said if the user want to replace the teddy bear in the example, the user should try to change the empty_prompt, but as you said the prompt is only used to synthesize the 3D scene, so it wouldn't work? In fact, I have tried the prompt you rise: a rabbit in Times Square, and it didn't work, what did I miss?

**Comment by zqh0253** [comment]
Yeah, the empty_prompt is only used to synthesize the Gaussians hidden behind the foreground. You still need to remove the foreground Gaussians for the replacement operation. This can be achieved by setting the opacity of the foreground Gaussians, indicated by ooi_masks, to 0.

**Comment by ALEX5874** [comment]
Thanks a lot! 
And could you tell me how to implement the effects in your paper? Like use “Move the girl, then delete the girl and Rotate the camera” to control the whole system?

**Comment by yyhyyhyyhyyh** [comment]
Sorry,if I want to remove the teddy bear I can set the ooi_masks to 0.But if I want to replace the teddy bear to other thing how can I get it. Or it can't be replaced?

**Comment by zqh0253** [comment]
You should use empty_prompt to indicate what's behind the teddy bear.
