### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Dumeowmeow** [zqh0253/3DitScene#17]
When training Gaussians to initialize background, the proj_mtx when initializing Gaussian with depth map are different from the proj_mtx used during training. Why aren't they consistent?
initialize with depth map:
<img width="359" alt="1729083836436" src="https://github.com/user-attachments/assets/36e63cf0-35bd-480c-b464-a0d1047aaef8">

when training the initial gaussians：
<img width="580" alt="f061e07cd82fbed4971ce928389f4fc" src="https://github.com/user-attachments/assets/293f09ea-83e8-438b-9958-73da6c45c13b">

**Comment by zqh0253** [comment]
Sorry for the confusion. The matrices are actually the same but are defined using different coordinate systems. During training, the [proj_mtx](https://github.com/zqh0253/3DitScene/blob/main/threestudio/data/uncond.py#L346) is defined with image coordinates ranging from -1 to 1. However, during initialization, the [proj_mtx](https://github.com/zqh0253/3DitScene/blob/main/custom/threestudio-3dgs/geometry/gaussian_base.py#L519) is defined with image coordinates from 0 to 0.5. You can also verify this as: 1.7321 = 2 * 1 / 2 ( * np.tan(fov / 2)).

**Comment by zqh0253** [comment]
Yes, the coordinates range from 0 to 1. I made a typo :)

As for the proj_mtx, could you please clarify why you would like to modify it?

**Comment by Dumeowmeow** [comment]
> Yes, the coordinates range from 0 to 1. I made a typo :)
> 
> As for the proj_mtx, could you please clarify why you would like to modify it?

Because I need to fit another system, so I have to change the matrix at [0,0] to its inverse.Then how should I change the initialization proj_mtx?By the way, I didn't find the usage of the ['proj_mtx'] in the following picture during training:
![image](https://github.com/user-attachments/assets/42249902-c683-4ee5-95e9-8413d825212d)
I think the proj_mtx during training is from this line:https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/custom/threestudio-3dgs/renderer/gaussian_batch_renderer.py#L23, then how could it correspond to the initialized proj_mtx with depth map?
