### ISSUE TITLE
About the image for reproducing results in demo page.

### ISSUE THREAD

**Issue by Colezwhy** [zqh0253/3DitScene#18]
Hi, thank you for your interesting work.
And I wonder where is the input image for the cherry.gif result? I want to make some experiments and trials on it.

**Comment by zqh0253** [comment]
https://pixart-alpha.github.io/PixArt-sigma-project/static/images/samples/others_webp/sample7.webp

**Comment by Colezwhy** [comment]
> https://pixart-alpha.github.io/PixArt-sigma-project/static/images/samples/others_webp/sample7.webp

Thanks for that. 
By the way, what does this line mean? Why *20+5, some empirical studies to normalize the depth from Geowizard or some?
https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/custom/threestudio-3dgs/geometry/gaussian_base.py#L507

**Comment by zqh0253** [comment]
Yes. They are just some empirical numbers to scale the predicted normalized depth.

**Comment by Colezwhy** [comment]
> Yes. They are just some empirical numbers to scale the predicted normalized depth.

Thank you! Congratulations on your good work.
I am closing this issue.
