### ISSUE TITLE
Training with larger azimuth range [-180, 180]

### ISSUE THREAD

**Issue by anita-hu** [zqh0253/3DitScene#3]
I am curious to hear if you have tried training with larger azimuth ranges (e.g. azimuth_range: [-180, 180]) and what the results are like. 
I am interested to see if this method is able to do 360 degree view synthesis. 

I have tried training with modified config but it seems the depth from self.geometry.project_pc(sample['c2w'], H=512, W=512) could be all zeros

**Comment by johnjojjjo** [comment]
Hi @zqh0253, could you please suggest a more specific process to make the current codebase to do the progressive expansion? Particularly, which functions we should modify and a short instruction to adjust each of them. Thank you.
