### ISSUE TITLE
Can 3D model be exported?

### ISSUE THREAD

**Issue by MontaEllis** [zqh0253/3DitScene#4]
Nice work! But can the modeled 3D model be exported?

**Comment by zqh0253** [comment]
Sure. `GaussianBaseModel` has a function called `save_ply` for saving the 3DGS.
To use it, you can add a line:
```
system.geometry.save_ply('gs.ply')
```
after [the optimization finishes](https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/launch.py#L244).

**Comment by MontaEllis** [comment]
Thanks a lot!

**Comment by MontaEllis** [comment]
I find the exported mesh has no texture.
![image](https://github.com/zqh0253/3DitScene/assets/37856372/34027b2a-5248-4a82-a419-4999a492659d)

**Comment by zqh0253** [comment]
This is 3DGS, and there is no texture here. You can use online 3DGS viewer (e.g. [antimatter15.com/splat/](antimatter15.com/splat/)) to see the result.

Optionally, you can use the function mentioned in https://github.com/zqh0253/3DitScene/issues/2#issuecomment-2139253416 to save the point cloud, and then view the colored point cloud in Meshlab.
