### ISSUE TITLE
What is the ooi_box argument in the optimization procedure?

### ISSUE THREAD

**Issue by moteloumka** [zqh0253/3DitScene#6]
Hi, first of all, thank you for sharing your code in such an innovative image generation approach!
Having ran the code with your teddy bear example, I'm trying to see how this works with some of my own, but I'm not completely sure what to provide to the ooi_box as arguments. In my understanding, if this is a box for identifying the main character, it would need 4 points with two coordinates each, yet in your example, there's only 4 points with one coordinate.
Could you please explain, what sort of argument i should provide to be able to test this on another image?

**Comment by zqh0253** [comment]
Hi, thanks for your interest in our work. The four numbers represent the coordinates of the bounding box's top-left and bottom-right corners.
<img width="569" alt="image" src="https://github.com/zqh0253/3DitScene/assets/32608622/d3c3a751-f964-40ea-b01e-d8b8c81f024c">

**Comment by moteloumka** [comment]
Super, thank you for your quick reply!
