### ISSUE TITLE
Where is the code to initialize the 3D Gaussian via the depth map

### ISSUE THREAD

**Issue by Dumeowmeow** [zqh0253/3DitScene#8]

**Comment by zqh0253** [comment]
Please refer to the code starting from [this line](https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/custom/threestudio-3dgs/geometry/gaussian_base.py#L592).

**Comment by Dumeowmeow** [comment]
But why inpaint here, and do masks[0] in line 618 refer to taking only one mask?

**Comment by zqh0253** [comment]
We use inpainting to handle the background area, allowing users to move and remove foreground objects without creating holes in the background.

`masks[0]` simply removes a redundant dimension, the same as `masks.squeeze(0)` operation. Actually we use several masks, as indicated by this [for loop](https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/custom/threestudio-3dgs/geometry/gaussian_base.py#L608).

**Comment by Dumeowmeow** [comment]
谢谢您的答复！但是我还有一个其他的问题想请教您，就是在初始化训练原图像的3D高斯的时候，为什么相机数据集会有方位角的变化呢，只有一张图像做监督的话，相机的角度不应该是定好的嘛。(初学者有点疑惑）

**Comment by zqh0253** [comment]
Learning from different camera perspectives can provide multi-view supervision, which leads to better 3D result. You can read [DreamFusion](https://dreamfusion3d.github.io/) to have a better understanding of this type of method.
